// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpJ6lC0UrIoAYEyMU_8e7S6rGwzpoCvc',
    appId: '1:144677968416:web:cb39702b85b305169c7a45',
    messagingSenderId: '144677968416',
    projectId: 'flutter-app-40b8c',
    authDomain: 'flutter-app-40b8c.firebaseapp.com',
    storageBucket: 'flutter-app-40b8c.appspot.com',
    measurementId: 'G-89D6EV0GYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOICu06_-I7XEH2Z9hMCj7zaTDCv1zw0M',
    appId: '1:144677968416:android:e8bf72b7bfcd68b79c7a45',
    messagingSenderId: '144677968416',
    projectId: 'flutter-app-40b8c',
    storageBucket: 'flutter-app-40b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96XawlitThIyOvvmBhHm40uSdfAzdp_4',
    appId: '1:144677968416:ios:caba4d2094de3a6a9c7a45',
    messagingSenderId: '144677968416',
    projectId: 'flutter-app-40b8c',
    storageBucket: 'flutter-app-40b8c.appspot.com',
    androidClientId: '144677968416-eqgb2o30ped8rhkhivh32sjm9d789ig0.apps.googleusercontent.com',
    iosClientId: '144677968416-vmavk059mafnn1hilebaeglilpnjep81.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA96XawlitThIyOvvmBhHm40uSdfAzdp_4',
    appId: '1:144677968416:ios:fd311e09906b2d8e9c7a45',
    messagingSenderId: '144677968416',
    projectId: 'flutter-app-40b8c',
    storageBucket: 'flutter-app-40b8c.appspot.com',
    androidClientId: '144677968416-eqgb2o30ped8rhkhivh32sjm9d789ig0.apps.googleusercontent.com',
    iosClientId: '144677968416-kf6p9ongcaichhan3ug6pktl93ge6kmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin.RunnerTests',
  );
}
